FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:24@sha256:e36c918ec9c679c18451231e277ea9122c00a097fb6e4a23c8c3d35bf08bbc3a

# Install Salesforce CLI globally for the node user.
RUN npm install -g @salesforce/cli@2.136.8 --no-audit --no-fund
