name: Codex Review Auto Comment

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  pull-requests: write

jobs:
  request-codex-review:
    runs-on: ubuntu-latest
    env:
      CODEX_REVIEW_COMMENTER_TOKEN: ${{ secrets.CODEX_REVIEW_COMMENTER_TOKEN }}
      CODEX_SKIP_AUTHOR: ${{ vars.CODEX_SKIP_AUTHOR }}
    steps:
      - name: Determine whether to request Codex review
        id: guard
        run: |
          set -o errexit
          skip=false
          reason=""
          if [ -z "${CODEX_REVIEW_COMMENTER_TOKEN}" ]; then
            skip=true
            reason="CODEX_REVIEW_COMMENTER_TOKEN secret is not configured"
          elif [ "${GITHUB_EVENT_ACTION}" = "opened" ] && [ -n "${CODEX_SKIP_AUTHOR}" ] && [ "${PR_AUTHOR}" = "${CODEX_SKIP_AUTHOR}" ]; then
            skip=true
            reason="PR opened by skip author (${CODEX_SKIP_AUTHOR})"
          fi
          echo "skip=${skip}" >> "$GITHUB_OUTPUT"
          if [ "$reason" != "" ]; then
            echo "reason=${reason}" >> "$GITHUB_OUTPUT"
            echo "Codex review auto comment skipped: ${reason}" >&2
          fi
        env:
          GITHUB_EVENT_ACTION: ${{ github.event.action }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      - name: Find existing Codex review comment
        if: steps.guard.outputs.skip != 'true'
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          token: ${{ env.CODEX_REVIEW_COMMENTER_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: '<!-- codex:dependabot-auto -->'
      - name: Ensure Codex review comment
        if: steps.guard.outputs.skip != 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ env.CODEX_REVIEW_COMMENTER_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          body: |-
            @codex review

            <!-- codex:dependabot-auto -->
          edit-mode: replace
