name: commitlint

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  lint-commits:
    name: Validate commit messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install commitlint deps
        run: |
          npm i -D @commitlint/cli @commitlint/config-conventional

      - name: Run commitlint on PR commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.mjs
