name: Dependabot Codex Review

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  request-codex-review:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      CODEX_REVIEW_COMMENTER_TOKEN: ${{ secrets.CODEX_REVIEW_COMMENTER_TOKEN }}
    steps:
      - name: Skip when PAT secret missing
        if: env.CODEX_REVIEW_COMMENTER_TOKEN == ''
        run: |
          echo "Dependabot Codex review trigger skipped: set CODEX_REVIEW_COMMENTER_TOKEN secret to enable @codex review comments." >&2
      - name: Find existing Codex review comment
        if: env.CODEX_REVIEW_COMMENTER_TOKEN != ''
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          token: ${{ env.CODEX_REVIEW_COMMENTER_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: '<!-- codex:dependabot-auto -->'
      - name: Ensure Codex review comment
        if: env.CODEX_REVIEW_COMMENTER_TOKEN != ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ env.CODEX_REVIEW_COMMENTER_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          body: |-
            @codex review

            <!-- codex:dependabot-auto -->
          edit-mode: replace
