name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Create release PR and tags
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          # Use manifest + config files in repo root
          manifest-file: .release-please-manifest.json
          config-file: release-please-config.json
          # Let release-please create tag + GitHub Release.
          # release.yml will edit the release to set pre-release flag
          # and upload VSIX assets based on odd/even policy.
