name: Release Please

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        # Pin action by commit SHA for supply-chain safety (tag v4)
        uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4
        with:
          # Use manifest config for advanced options (v4)
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: main
          # Use a PAT if provided to allow fork-based PRs when org policy blocks bot PRs
          token: ${{ secrets.RELEASE_PLEASE_TOKEN || github.token }}
          fork: ${{ secrets.RELEASE_PLEASE_TOKEN != '' }}
          # Fallback: if no PAT, skip PR creation to avoid
          # "Actions not permitted to create or approve PRs" policy errors
          skip-github-pull-request: ${{ secrets.RELEASE_PLEASE_TOKEN == '' }}
