name: Release Please

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          package-name: apex-log-viewer
          changelog-path: CHANGELOG.md
          default-branch: main
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true

