name: release-please

on:
  workflow_dispatch:
    inputs:
      release-as:
        description: 'Optional SemVer override (e.g. 1.2.3); leave blank for auto'
        required: false
        type: string
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    name: Prepare release PR or publish release
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          command: manifest
          release-as: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release-as || '' }}
